
package world {

    class World {

    }

}

package building {

    class Tower <<Node3D>> {
        + {signal} floors_changed(floors_amount: int)
        + push_block(type: BlockType, connection_quality: ConnectionQuality) -> void
        + pop_block(index: int) -> BuildingNode
    }

    class TowerBlock <<RefCounted>> {
        + get_cost() -> int
        + get_block_type() -> BlockType
        + get_dwellers_amount() -> int
        + get_connection_quality() -> ConnectionQuality
    }

    Tower -* TowerBlock

    enum FlyEndReason {
        TOUCHED_TOWER,
        FLEW_OFF,
        TOUCHED_GROUND
    }

    class BlockEntity <<Node3D>> {
        {signal} fly_ended(reason: FlyEndReason)
        {async} drop() -> FlyEndReason
        {async} throw(direction: Vector3, force: float) -> void
    }

    BlockEntity -- FlyEndReason

    enum BlockKind {
        BASE,
        COMMON,
        ROOF
    }

    class BlockType <<Resource>> {
        - _cost_calculator: BlockCostCalculator
        + get_packed_model() -> PackedScene
        + get_block_kind() -> BlockKind
        + get_max_dwellers() -> int
        + calculate_cost(building_node: BuildingNode) -> int
    }

    package crane {

        class Crane <<Node3D>> {
            + set_block_type(type: BlockType)
            + set_anchor_rotation(anchor_rotation: CraneAnchorRotation)
        }

        abstract class CraneAnchorRotation <<Resource>> {
            + apply(block: Node3D)
        }

        class DefaultAnchorRotation extends CraneAnchorRotation {
            + _init(world: World)
        }

    }

    class Building <<Node3D>> {
        + {async} release_block() -> FlyEndReason
        + get_tower() -> Tower
        + get_crane() -> Crane
    }

    Building -* Crane
    Building -* BlockEntity
    Building -* Tower

    BlockType -- TowerBlock
    BlockType -- BlockKind

}
