
package world {

    class World {
        + get_tower() -> Tower
        + get_weather_manager() -> WeatherManager
        + get_time_manager() -> TimeManager
        + get_enviroment() -> Enviroment
        + set_wind_force(value: float) -> void
        + get_wind_force() -> float
    }

}

package map {

    class Enviroment {
        + set_sky_color(value: Color)
        + set_clouds_color(value: Color)
        + set_fog_visible(value: boolean)
        + set_rain_visible(value: boolean)
    }

}

package weather {

    class WeatherStateEntry <<Resource>> {
        - {export} _transitions: Array[String]
        - {export} _weather_type: WeatherType
        + next_transition() -> String
        + get_weather_type() -> WeatherType
    }

    class WeatherScheduler {
        - {export} _transitions: Dictionary[String, WeatherStateEntry]
        + {signal} gonna_change_weather(weather: Weather)
        + get_current_weather() -> Weather
    }

    class Weather {
        get_type() -> WeatherType
    }

    class WeatherType <<Resource>> {
        + icon: Texture2D
        + name: String
        + tower_affector: TowerAffector
        + enviroment_affector: EnviromentAffector
    }

    abstract class EnviromentAffector <<Resource>> {
        affect(enviroment: Enviroment)
    }

    abstract class TowerAffector <<Resource>> {
        affect(tower: Tower)
    }

    WeatherType -- EnviromentAffector
    WeatherType -- TowerAffector

}

package time {

    enum TimesOfDay {
        MORNING,
        AFTERNOON,
        EVENING,
        NIGHT
    }

    class TimeManager <<Node>> {
        + {signal} time_tick(current_time: Time)
        + {signal} time_of_day_changed(time_of_day: TimesOfDay)
        + ctor(start_from: Time, ticker: TimeTicker)
        + get_current_time() -> Time
        + get_time_of_day() -> TimesOfDay
    }

    class TimeTicker {
        + {signal} tick()
    }

    class Time <<RefCounted>> {
        + ctor(hours: int, minutes: int)
        + get_hours()
        + get_minutes()
    }

    TimeManager -- Time

}
